# Generated by Django 4.2.8 on 2024-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('icon', models.ImageField(upload_to='image')),
                ('iconBg', models.CharField(max_length=500)),
                ('linkicon', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=500)),
                ('points', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconUrl', models.ImageField(upload_to='image')),
                ('theme', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
